# Generated by Django 4.0.3 on 2022-03-19 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_document_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='image',
        ),
    ]
